"""Unified LLM client based on OpenAI-compatible HTTP API.

This module supports DeepSeek, Qwen, and OpenAI providers.
"""

from __future__ import annotations

import logging
import math
import os
import random
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any

import httpx

LOGGER = logging.getLogger(__name__)
DEFAULT_TIMEOUT_SECONDS = 60.0


@dataclass
class Usage:
    """Token usage information returned by the model provider.

    Attributes:
        prompt_tokens: Number of input tokens.
        completion_tokens: Number of output tokens.
        total_tokens: Total number of tokens.
        estimated: True when usage is estimated locally.
    """

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    estimated: bool = False


@dataclass
class LLMResponse:
    """Unified response payload for all providers.

    Attributes:
        content: Text generated by the model.
        usage: Token usage statistics.
        raw_response: Raw provider response for debugging.
    """

    content: str
    usage: Usage
    raw_response: dict[str, Any] | None = None


@dataclass
class ProviderConfig:
    """Runtime config for one model provider."""

    provider_name: str
    api_key: str
    base_url: str
    model: str
    timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS


class LLMProvider(ABC):
    """Abstract interface for chat-capable model providers."""

    @abstractmethod
    def chat(self, messages: list[dict[str, str]], temperature: float = 0.2) -> LLMResponse:
        """Send chat messages and return a unified response."""


class ResponseFormatError(ValueError):
    """Raised when provider response format is invalid for parsing."""


class OpenAICompatibleProvider(LLMProvider):
    """Provider implementation for OpenAI-compatible chat APIs."""

    def __init__(self, config: ProviderConfig):
        self._config = config

    def chat(self, messages: list[dict[str, str]], temperature: float = 0.2) -> LLMResponse:
        """Call `/chat/completions` with httpx and parse unified response."""
        url = f"{self._config.base_url.rstrip('/')}/chat/completions"
        payload = {
            "model": self._config.model,
            "messages": messages,
            "temperature": temperature,
        }
        headers = {
            "Authorization": f"Bearer {self._config.api_key}",
            "Content-Type": "application/json",
        }
        timeout = httpx.Timeout(self._config.timeout_seconds)

        with httpx.Client(timeout=timeout) as client:
            response = client.post(url, headers=headers, json=payload)
            response.raise_for_status()
            data = response.json()

        try:
            choice = data["choices"][0]["message"]
        except (KeyError, IndexError, TypeError) as exc:
            raise ResponseFormatError("Provider response missing choices[0].message") from exc
        content = choice.get("content", "")
        if not isinstance(content, str):
            raise ResponseFormatError("Provider response content is not a string")
        usage = _extract_usage(data, messages, content)
        return LLMResponse(content=content, usage=usage, raw_response=data)


def _extract_usage(data: dict[str, Any], messages: list[dict[str, str]], content: str) -> Usage:
    """Extract usage from API response, fallback to local estimation."""
    usage_data = data.get("usage")
    if isinstance(usage_data, dict):
        prompt_tokens = int(usage_data.get("prompt_tokens", 0))
        completion_tokens = int(usage_data.get("completion_tokens", 0))
        total_tokens = int(usage_data.get("total_tokens", prompt_tokens + completion_tokens))
        return Usage(
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=total_tokens,
            estimated=False,
        )

    prompt_tokens = estimate_tokens(" ".join(msg.get("content", "") for msg in messages))
    completion_tokens = estimate_tokens(content)
    return Usage(
        prompt_tokens=prompt_tokens,
        completion_tokens=completion_tokens,
        total_tokens=prompt_tokens + completion_tokens,
        estimated=True,
    )


def estimate_tokens(text: str) -> int:
    """Estimate token count with a simple char-based heuristic."""
    if not text:
        return 0
    # A practical rough rule: English average is around 4 chars per token.
    return max(1, math.ceil(len(text) / 4))


def calculate_cost_usd(provider: str, usage: Usage, model: str | None = None) -> float:
    """Estimate cost in USD based on provider/model pricing table.

    The pricing table is intentionally small and can be overridden by passing
    `LLM_MODEL` environment variable when needed.
    """

    provider_key = provider.lower()
    selected_model = (model or "").lower()

    pricing = {
        "deepseek": {"input_per_1k": 0.00014, "output_per_1k": 0.00028},
        "qwen": {"input_per_1k": 0.00040, "output_per_1k": 0.00120},
        "openai": {"input_per_1k": 0.00015, "output_per_1k": 0.00060},
    }

    # Keep behavior simple: use provider-level pricing by default.
    # If model-specific pricing is needed later, extend this branch.
    _ = selected_model
    if provider_key not in pricing:
        LOGGER.warning("Unknown provider for cost estimation: %s", provider)
        return 0.0

    rates = pricing[provider_key]
    input_cost = usage.prompt_tokens / 1000 * rates["input_per_1k"]
    output_cost = usage.completion_tokens / 1000 * rates["output_per_1k"]
    return round(input_cost + output_cost, 8)


def build_provider_from_env() -> LLMProvider:
    """Build provider from environment variables.

    Env:
        LLM_PROVIDER: deepseek | qwen | openai (default: deepseek)
        DEEPSEEK_API_KEY / QWEN_API_KEY / OPENAI_API_KEY
        LLM_MODEL: optional, override default model
        LLM_BASE_URL: optional, override provider endpoint
    """

    provider_name = os.getenv("LLM_PROVIDER", "deepseek").strip().lower()
    defaults = {
        "deepseek": {
            "env_key": "DEEPSEEK_API_KEY",
            "base_url": "https://api.deepseek.com/v1",
            "model": "deepseek-chat",
        },
        "qwen": {
            "env_key": "QWEN_API_KEY",
            "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
            "model": "qwen-plus",
        },
        "openai": {
            "env_key": "OPENAI_API_KEY",
            "base_url": "https://api.openai.com/v1",
            "model": "gpt-4o-mini",
        },
    }

    if provider_name not in defaults:
        raise ValueError(f"Unsupported LLM_PROVIDER: {provider_name}")

    provider_defaults = defaults[provider_name]
    env_key = provider_defaults["env_key"]
    api_key = os.getenv(env_key) or os.getenv("API_KEY")
    if not api_key:
        raise ValueError(f"Missing API key. Please set {env_key} (or API_KEY).")

    config = ProviderConfig(
        provider_name=provider_name,
        api_key=api_key,
        base_url=os.getenv("LLM_BASE_URL", provider_defaults["base_url"]),
        model=os.getenv("LLM_MODEL", provider_defaults["model"]),
        timeout_seconds=DEFAULT_TIMEOUT_SECONDS,
    )
    return OpenAICompatibleProvider(config)


def create_provider() -> LLMProvider:
    """Backward-compatible alias used by pipeline entrypoints."""
    return build_provider_from_env()


def _extract_status_code(exc: Exception) -> int | None:
    if not isinstance(exc, httpx.HTTPStatusError):
        return None
    try:
        return int(exc.response.status_code)
    except Exception:
        return None


def is_retryable_error(exc: Exception) -> bool:
    """Return True when an error is likely recoverable by retrying."""
    if isinstance(exc, ResponseFormatError):
        return False
    if isinstance(exc, httpx.HTTPStatusError):
        status_code = _extract_status_code(exc)
        if status_code is None:
            return False
        return status_code == 429 or 500 <= status_code < 600
    if isinstance(exc, (httpx.TimeoutException, httpx.RequestError)):
        return True
    return False


def _compute_retry_delay_seconds(
    attempt: int,
    base_delay_seconds: float,
    max_delay_seconds: float,
    jitter_min: float,
    jitter_max: float,
    random_fn: Any = random.uniform,
) -> float:
    # attempt is 1-based and this function is only called before the next retry.
    exponential_delay = base_delay_seconds * (2 ** (attempt - 1))
    capped_delay = min(exponential_delay, max_delay_seconds)
    jitter = max(jitter_min, float(random_fn(jitter_min, jitter_max)))
    return capped_delay * jitter


def _safe_log_value(value: str) -> str:
    normalized = str(value or "").strip()
    if normalized:
        return normalized
    return "<missing>"


def chat_with_retry(
    provider: LLMProvider,
    messages: list[dict[str, str]],
    temperature: float = 0.2,
    max_retries: int = 3,
    base_delay_seconds: float = 1.0,
    max_delay_seconds: float = 20.0,
    jitter_min: float = 1.0,
    jitter_max: float = 1.5,
    item_title: str = "",
    item_url: str = "",
) -> LLMResponse:
    """Call provider chat with retry and exponential backoff."""
    if max_retries < 1:
        raise ValueError("max_retries must be >= 1")
    if jitter_min < 1.0 or jitter_max < jitter_min:
        raise ValueError("jitter range must be >=1.0 and jitter_max >= jitter_min")

    for attempt in range(1, max_retries + 1):
        try:
            return provider.chat(messages=messages, temperature=temperature)
        except (httpx.HTTPError, ResponseFormatError) as exc:
            safe_title = _safe_log_value(item_title)
            safe_url = _safe_log_value(item_url)
            status_code = _extract_status_code(exc)
            error_type = type(exc).__name__
            retryable = is_retryable_error(exc)
            if not retryable:
                LOGGER.error(
                    "Chat failed with non-retryable error. title=%s url=%s attempt=%s/%s "
                    "error_type=%s status_code=%s",
                    safe_title,
                    safe_url,
                    attempt,
                    max_retries,
                    error_type,
                    status_code,
                )
                raise
            if attempt >= max_retries:
                LOGGER.error(
                    "Chat retries exhausted; abandoning item. title=%s url=%s attempt=%s/%s "
                    "error_type=%s status_code=%s final_abandon=true",
                    safe_title,
                    safe_url,
                    attempt,
                    max_retries,
                    error_type,
                    status_code,
                )
                raise
            delay = _compute_retry_delay_seconds(
                attempt=attempt,
                base_delay_seconds=base_delay_seconds,
                max_delay_seconds=max_delay_seconds,
                jitter_min=jitter_min,
                jitter_max=jitter_max,
            )
            LOGGER.warning(
                "Chat retry scheduled. title=%s url=%s attempt=%s/%s error_type=%s status_code=%s "
                "retry_in=%.2fs",
                safe_title,
                safe_url,
                attempt,
                max_retries,
                error_type,
                status_code,
                delay,
            )
            time.sleep(delay)

    raise RuntimeError("Unreachable retry branch reached.")


def quick_chat(
    prompt: str,
    system_prompt: str = "You are a helpful assistant.",
    temperature: float = 0.2,
) -> LLMResponse:
    """One-line helper to call the configured LLM."""
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": prompt},
    ]
    provider = build_provider_from_env()
    return chat_with_retry(provider=provider, messages=messages, temperature=temperature)


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s [%(name)s] %(message)s",
    )
    test_prompt = os.getenv("QUICK_CHAT_PROMPT", "请用一句话介绍你自己。")

    try:
        response = quick_chat(test_prompt)
        provider_name = os.getenv("LLM_PROVIDER", "deepseek")
        estimated_cost = calculate_cost_usd(provider=provider_name, usage=response.usage)

        LOGGER.info("Model reply: %s", response.content)
        LOGGER.info(
            "Usage: prompt=%s completion=%s total=%s estimated=%s",
            response.usage.prompt_tokens,
            response.usage.completion_tokens,
            response.usage.total_tokens,
            response.usage.estimated,
        )
        LOGGER.info("Estimated cost (USD): %.8f", estimated_cost)
    except Exception:
        LOGGER.exception("Quick chat test failed.")
